### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rusty-machine#81]
Error handling is pretty poor at the moment. Lots of functions can panic which should perhaps be replaced with `Result` and `Option`.

This issue should track some of this work and provide a central spot for reporting instances of _panic abuse_.

**Known issues:**

- [x] Decomposition should return results instead of panicking. See #16 .
- [x] The `with_weights` constructor introduced by #79 . 
- [x] Initialization in K-means can cause invalid states. As described in #60 .

**Other tasks:**

- [x] Create a new `error` module to handle errors in the learning module.
- [x] Create a new `error` module to handle errors in the linalg module.
- [x] Make the `train` functions in `SupModel` and `UnSupModel` return a Result. Training can fail - not panicking would be nice...

**Comment by AtheMathmo** [comment]
I made the decision to keep the `with_weights` constructor panicking. I'll close this out but error handling should still get some attention!
